version: '3'
services:
  app:
    container_name: hbu_box_app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:80"
    env_file:
      - .env