spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    hikari:
      maximum-pool-size: 20
    url: jdbc:postgresql://${POSTGRES_DB_HOST}:5432/${POSTGRES_DB}?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
  cloud:
    aws:
      S3:
        bucket: ${BUCKET_NAME}
      stack.auto: false
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${ACCESS_KEY_ID}
        secret-key: ${ACCESS_SECRET}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 2GB
      max-request-size: 2GB
  security:
    user:
      name: ${SECURITY_USER}
      password: ${SECURITY_PASSWORD}
server:
  servlet:
    context-path: /api
  tomcat:
    connection-timeout: 300000

  port: 8080
  address: 0.0.0.0
  forward-headers-strategy: native