services:
  db:
    image: postgres:15
    restart: always
    container_name: hanbat-db
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - hbu_net
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - "8000:8080"
    depends_on:
      - db
    restart: always
    networks:
      - hbu_net

networks:
  hbu_net:

volumes:
  db_data: